### ISSUE TITLE
Green X's are supposed to be checks

### ISSUE THREAD

**Issue by cmcculloh-kr** [chriscorwin/fuelux-mctheme#11]
![image](https://cloud.githubusercontent.com/assets/8006971/5978922/5a51c534-a871-11e4-8390-e2f710fcecac.png)

**Comment by chriscorwin** [comment]
fixed.

**Comment by chriscorwin** [comment]
wait, not fixed. 

green Xs ?

that's stupid.

**Comment by chriscorwin** [comment]
OH, never mind, your dumb screenshot is backwards, AGAIN.
