### ISSUE TITLE
Vertical grey line too thick next to "Go!"

### ISSUE THREAD

**Issue by cmcculloh-kr** [chriscorwin/fuelux-mctheme#12]
![image](https://cloud.githubusercontent.com/assets/8006971/5978941/6e875226-a871-11e4-826b-572db28bdd07.png)

![image](https://cloud.githubusercontent.com/assets/8006971/5978948/806722dc-a871-11e4-9a67-2246ac238500.png)

http://0.0.0.0:8000/examples/bootstrap-components/bootstrap-components.html?

"Button Addons" section.

**Comment by cmcculloh-kr** [comment]
Here too (same page, next two sections):

![image](https://cloud.githubusercontent.com/assets/8006971/5979004/f797ee72-a871-11e4-8636-239c773eb879.png)

**Comment by chriscorwin** [comment]
Can't reproduce:

![screenshot 2015-01-30 12 22 39](https://cloud.githubusercontent.com/assets/362417/5980051/b7eaf7a2-a87a-11e4-945f-90816b4e65ef.png)
