### ISSUE TITLE
Contextual Icons missing grey border

### ISSUE THREAD

**Issue by cmcculloh-kr** [chriscorwin/fuelux-mctheme#13]
![image](https://cloud.githubusercontent.com/assets/8006971/5978972/b4527858-a871-11e4-8fc6-8553850e2a47.png)

"there are no borders in the style guide. we have outstanding redlines for that one in apps. contacts particularly"

**Comment by swilliamset** [comment]
for reference https://github.com/ExactTarget/fuelux-mctheme/issues/92
