### ISSUE TITLE
Inline disabled checkbox getting cut off on left side

### ISSUE THREAD

**Issue by cmcculloh-kr** [chriscorwin/fuelux-mctheme#14]
![image](https://cloud.githubusercontent.com/assets/8006971/5979182/770c0bec-a873-11e4-9f04-0ad7ff284ff8.png)

**Comment by chriscorwin** [comment]
I can't reproduce this.

**Comment by cmcculloh-kr** [comment]
Apparently it all depends on how narrow your window is. Put it super narrow and slowly widen and you'll see it happen sporadically. The width I had was _just perfect_ to make this bug happen.

**Comment by chriscorwin** [comment]
Too bad then.

**Comment by interactivellama** [comment]
Sounds like some kind of sub-pixel anti-aliasing.
