### ISSUE TITLE
Text in scheduler controls is black instead of blue

### ISSUE THREAD

**Issue by cmcculloh-kr** [chriscorwin/fuelux-mctheme#17]
![image](https://cloud.githubusercontent.com/assets/8006971/5979567/c458f222-a876-11e4-90c6-b23919172100.png)

**Comment by cmcculloh-kr** [comment]
I think it's just that selectlist actually has the wrong color text:

![image](https://cloud.githubusercontent.com/assets/8006971/5979614/4384236e-a877-11e4-8555-62f836301554.png)

**Comment by chriscorwin** [comment]
Master is incorrect. The select list is supposed to be black text.
