### ISSUE TITLE
Repeater: View Icons

### ISSUE THREAD

**Issue by mbeard** [chriscorwin/fuelux-mctheme#2]
The size of the repeater view icons need to be reduced so that the height of buttons is equal to the height of the filter dropdown.

![screenshot 2015-01-28 13 10 43](https://cloud.githubusercontent.com/assets/467352/5943700/36b5eb10-a6ef-11e4-9e2c-da8e19f3c8e8.png)

**Comment by chriscorwin** [comment]
I'm looking at this right now — it seems, when compared with the spec, that are several things off here:
- The icons are actually too small: they're supposed to be 18px x 18px, and they're currently 16px x 16px
- The icons have too much padding around them, making the overall button size too big
- The filter drop down is too small, either not big enough text, not enough vertical padding, or both.

![repeater-view-icons-from-spec](https://cloud.githubusercontent.com/assets/362417/5944380/88b94af6-a6f4-11e4-83d9-770d50ee1af9.png)

**Comment by chriscorwin** [comment]
Fixed, here it is now:

![repeater-view-icons-fixed](https://cloud.githubusercontent.com/assets/362417/5945599/ca0c7ee8-a6fd-11e4-8691-9a793999d2f8.png)
