### ISSUE TITLE
svg icons not supported in current fuelux-pages icon sheet

### ISSUE THREAD

**Issue by swilliamset** [chriscorwin/fuelux-mctheme#20]
http://fuelux-pages.herokuapp.com/general/icons/?id=1bfbde34-0f6e-4d5f-1111-5a9afad1f58a

removing `icon.css` is the first step but still needs additional adjustment. 

@mbeard suggest this **SHOULD NOT** prevent us from releasing the svg icons. agree?

![screen shot 2015-02-03 at 10 53 14 am](https://cloud.githubusercontent.com/assets/347227/6023470/fc361fd4-ab92-11e4-82f6-b2d4b7c6371a.png)

**Comment by chriscorwin** [comment]
I totally agree, it should not. It's an issue in `fuelux-pages` not an issue with the SVG icons, nor with `fuelux-mctheme`.

Is it important to do, and do well? Yes.

Should it prevent the release of the icons?

No.

$0.02.

**Comment by mbeard** [comment]
I agree.  We should remove both of the iconography and typography pages from fuelux-pages.  Those we're just put in temporarily.... I have removed those pages now.

**Comment by chriscorwin** [comment]
Well, that's weird.
