### ISSUE TITLE
Repeater: Clear Search Icon

### ISSUE THREAD

**Issue by mbeard** [chriscorwin/fuelux-mctheme#4]
When searching in the repeater, not seeing the clear icon (e.g. x) after searching.

Seeing this:
![screenshot 2015-01-28 13 18 38](https://cloud.githubusercontent.com/assets/467352/5943840/450127b0-a6f0-11e4-8f67-8e509df66088.png)

Instead of:
![screenshot 2015-01-28 13 19 46](https://cloud.githubusercontent.com/assets/467352/5943849/5e664e88-a6f0-11e4-861e-c8d632b1e899.png)

Also, the focused state of the search probably shouldn't show the pressed icon state.

**Comment by chriscorwin** [comment]
Fixed.
