### ISSUE TITLE
Tree height changed by larger icons

### ISSUE THREAD

**Issue by chriscorwin** [chriscorwin/fuelux-mctheme#6]
The tree's icons are making it too tall -- may need to adjust bottom margins and/or icons sizes.

![tree-wrong-height](https://cloud.githubusercontent.com/assets/362417/5959447/64c0b398-a79c-11e4-9489-8b9b44f7b596.png)

On the left is SVG, on the right is the old bitmap.

**Comment by futuremint** [comment]
Also the SVG "arrows" on the left are missing that small bottom highlight (the 1px white line just inside the bottom border)

**Comment by chriscorwin** [comment]
Fixed.
