### ISSUE TITLE
Disabled state of checkbox & radio are too light

### ISSUE THREAD

**Issue by futuremint** [chriscorwin/fuelux-mctheme#7]
![compairison](https://cloud.githubusercontent.com/assets/5891/5959518/078b8576-a79d-11e4-8dfa-cb0c5d8cfbaa.png)

**Comment by chriscorwin** [comment]
Fixed ---- the issue was that I had made 50% opacity icons for disabled, and the CSS was _also_ dimming them by 50%.

Fixed by making the icons 100%.
